# Generated by Django 5.1.3 on 2024-12-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField()),
            ],
            options={
                'db_table': 'produts_colour',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feature',
            name='fabric',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='feature',
            name='fit',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='feature',
            name='neck',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='feature',
            name='pattern',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='feature',
            name='sleeves',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='feature',
            name='style',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.ManyToManyField(related_name='products', to='products.colour'),
        ),
    ]
