# Generated by Django 5.1.3 on 2024-12-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='updated_at',
        ),
    ]
