# Generated by Django 5.1.3 on 2024-12-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
